---

namespace: 'biptec'
name: 'opnsense'
version: 1.2.6
readme: 'README.md'
authors:
  - 'AnsibleGuy <guy@ansibleguy.net>'
description: "Ansible Collection to manage OPNSense firewalls using their API"
license_file: 'LICENSE.txt'
tags:
  - 'firewall'
  - 'api'
  - 'opnsense'
  - 'iac'
  - 'network'
  - 'security'
  - 'filter'
dependencies: {}
repository: 'https://github.com/biptec/ansible-collection-opnsense'
documentation: 'https://opnsense.ansibleguy.net'
homepage: 'https://ansibleguy.net'
issues: 'https://github.com/biptec/ansible-collection-opnsense'
build_ignore: []
